version: "3"
services:
  tiktok_scrapper:
    build:
      context: .
      args:
        - BUILD_NO_CACHE=true # Add this line to enable --no-cache
    platform: linux/amd64
    environment:
      - "TZ=Asia/Kolkata"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - headless_chrome

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"

  headless_chrome:
    image: browserless/chrome:latest
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - "3000:3000"
    container_name: headless_browser
